version: "3.7"

services:
  server:
    image: vaultwarden/server:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      ROCKET_PORT: 8089
